### ISSUE TITLE
upx compression did not run

### ISSUE THREAD

**Issue by ds2k5** [hemu312/memory#2]
Hi,
Added this lines to Cargo.toml
because the bin file was 15mb 

```
[profile.release]
opt-level = 'z'     # Optimize for size
lto = true          # Enable link-time optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary*

```

when try to get it smaller

`upx compress --brute target/release/memory
`

the binary did not run
```


$ upx compress --brute memory
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: compress: FileNotFoundException: compress: No such file or directory
   6468712 ->   2089084   32.30%   linux/amd64   memory                       

Packed 1 file.

```

**Comment by hemu312** [comment]
Sir, 
I followed same steps as you, packed binary is working for me.
![Screenshot_20240805_124638](https://github.com/user-attachments/assets/73e4cb20-0b07-4eef-a1df-7ad225f2ef0c)

**Comment by ds2k5** [comment]
@hemu312 

Ok thanks for your info 

for me did not work

1. cargo build --release
2. cp target/release/memory .
3. ./memory -> runs  size 6.2M
4. upx --brute memory
5. ./memory  -> did not run     size 2 M

only upx --best work but bin is  2.5M
can see in the head of the file

```
head -2 memory
h�bh�bP�� �ELF>�6��@/��bG&8UUPX!�	

```

in the file compressed with "--brute" did no see  "UPX!" in the 1st Line

UPX Version 3.96

**Comment by ds2k5** [comment]
Found it - it was the Version of UPX
used the newer Version: 4.2.4 not it works with "--brute" too!

thanks
